// IMPORT { FAICON } FROM "./FONTAWESOME/THIN/ICON.JS"
// IMPORT { SLOT } FROM "EXPO-ROUTER"
// IMPORT { SVG AS REACTNATIVESVG, PATH AS REACTNATIVEPATH } FROM "REACT-NATIVE-SVG"
// IMPORT * AS COMMON FROM "./COMMON.TS"
// IMPORT * AS EXPODEVICE FROM "EXPO-DEVICE"
// IMPORT * AS EXPOFILESYSTEM FROM "EXPO-FILE-SYSTEM"
// IMPORT * AS EXPOIMAGEMANUPULATOR FROM "EXPO-IMAGE-MANIPULATOR"
// IMPORT * AS EXPOLOCALIZATION FROM "EXPO-LOCALIZATION"
// IMPORT * AS EXPONAVIGATIONBAR FROM "EXPO-NAVIGATION-BAR"
// IMPORT * AS EXPOSTATUSBAR FROM "EXPO-STATUS-BAR"
// IMPORT * AS REACTNATIVEIMAGEPICKER FROM "EXPO-IMAGE-PICKER"
// IMPORT TRANSLATION FROM "./TRANSLATION.JS"
// IMPORT REACT, { USESTATE AS USECONTEXT, USEREF, FORWARDREF, USEEFFECT } FROM "REACT"
// IMPORT REACTNATIVE, { PRESSABLE, ANIMATED, PANRESPONDER, EASING, SCROLLVIEW, PLATFORM, KEYBOARD, BACKHANDLER, DIMENSIONS, IMAGE AS REACTNATIVEIMAGE, ACCESSIBILITYINFO, STATUSBAR } FROM "REACT-NATIVE"
// EXPORT { STATUSBAR }
// EXPORT { EXPONAVIGATIONBAR, EXPOSTATUSBAR, EXPOFILESYSTEM, EXPOLOCALIZATION, EXPOIMAGEMANUPULATOR, EXPODEVICE }
// EXPORT { USECONTEXT, USEREF }
// EXPORT * AS COMMON FROM "./COMMON.TS"
// EXPORT CLASS PACKMANAGER { // CREATE ONCE ON PAGE
//   PAKCS = []
//   TOUCHINGCOMPONENTID
//   ONTOUCHENDTHROTTLEID = COMMON.MAKESAUTOINDEX()
// }
// EXPORT CLASS PROTOTYPE {
//   "_NO"
// }
// EXPORT CLASS ANIMATALSCROLLVIEWPACK EXTENDS (PROTOTYPEPACK AS NEW (PROPS) => PICK<PROTOTYPEPACK<{
//   CHILDREN,
//   STYLE,
// }>, 
// "_CREATELAYOUTELEMENT" |
// "_DOONSCROLLS" |
// "_DOONTOUCHENDS" |
// "_DOONTOUCHMOVES" |
// "_DOONTOUCHSTARTS" |
// "_REGISTERKEYBOARDEVENTS" |
// "_USEREF" |
// "_USERENDER" |
// "ACCESSIBILITYACTIONS" |
// "ACCESSIBILITYLABEL" |
// "ASSIGNSTYLE" |
// "CONTENTCONTAINERSTYLE" |
// "PROPS" |
// "GETREF" |
// "STYLE" 
// >) {
//   VARRUCTOR(PROPS) {
//     SUPER(PROPS)
//     THIS.ASSIGNSTYLE({
//       MARGIN: 0,
//       PADDING: 0,
//       BOXSIZING: "BORDER-BOX",
//       OVERFLOW: "AUTO",
//       OPACITY: 0,
//       POSITION: "absOLUTE",
//     })
//     THIS._REGISTERKEYBOARDEVENTS()
//   }
//   RENDER() {
//     VAR A
//     THIS._USEREF()
//     THIS._USERENDER()
//     A = THIS._CREATELAYOUTELEMENT(THIS.PROPS)
//     THIS.ASSIGNSTYLE(THIS.PROPS.STYLE)
//     IF (A == UNDEFINED) {
//       THIS.ASSIGNSTYLE({
//         OPACITY: 1,
//       })
//       A = (
//         <ANIMATED.SCROLLVIEW
//           ACCESSIBILITYACTIONS={ THIS.ACCESSIBILITYACTIONS }
//           ACCESSIBILITYLABEL={ THIS.ACCESSIBILITYLABEL }
//           CONTENTCONTAINERSTYLE={ THIS.CONTENTCONTAINERSTYLE }
//           ONSCROLL={ THIS._DOONSCROLLS }
//           ONTOUCHEND={ THIS._DOONTOUCHENDS }
//           ONTOUCHMOVE={ THIS._DOONTOUCHMOVES }
//           ONTOUCHSTART={ THIS._DOONTOUCHSTARTS }
//           REF={ THIS.GETREF() }
//           STYLE={ THIS.STYLE }
//         >
//           { THIS.PROPS.CHILDREN }
//         </ANIMATED.SCROLLVIEW>
//       )
//     }
//     RETURN A
//   }
// }
// EXPORT CLASS ANIMATALVIEWPACK EXTENDS (PROTOTYPEPACK AS NEW (PROPS) => PICK<PROTOTYPEPACK<{
//   CHILDREN
//   [KEY: STRING]: ANY
// }>, 
// "_CREATELAYOUTELEMENT" |
// "_DOONTOUCHENDS" |
// "_DOONTOUCHMOVES" |
// "_DOONTOUCHSTARTS" |
// "_REGISTERKEYBOARDEVENTS" |
// "_USEREF" |
// "_USERENDER" | 
// "ADDONTOUCHEND" |
// "ADDONTOUCHMOVE" |
// "ADDONTOUCHSTART" |
// "ASSIGNSTYLE" |
// "GETREF" |
// "PROPS" |
// "REND" |
// "GETREST" |
// "STYLE" 
// >) {
//   VARRUCTOR(PROPS) {
//     SUPER(PROPS)
//     THIS.ASSIGNSTYLE({
//       BOXSIZING: "BORDER-BOX",
//       DISPLAY: "BLOCK",
//       MARGIN: 0,
//       OPACITY: 0,
//       OVERFLOW: "AUTO",
//       PADDING: 0,
//       POSITION: "absOLUTE",
//     })
//     THIS._REGISTERKEYBOARDEVENTS()
//   }
//   RENDER() {
//     VAR A
//     THIS._USEREF()
//     THIS._USERENDER()
//     A = THIS._CREATELAYOUTELEMENT(THIS.PROPS)
//     IF (A == UNDEFINED) {
//       THIS.ASSIGNSTYLE({
//         OPACITY: 1,
//       })
//       A = (
//         <ANIMATED.VIEW
//           ONTOUCHEND={ THIS._DOONTOUCHENDS }
//           ONTOUCHMOVE={ THIS._DOONTOUCHMOVES }
//           ONTOUCHSTART={ THIS._DOONTOUCHSTARTS }
//           REF={ THIS.GETREF() }
//           STYLE={ THIS.STYLE }
//           { ...THIS.GETREST() }
//         >
//           { THIS.PROPS.CHILDREN }
//         </ANIMATED.VIEW>
//       )
//     }
//     RETURN A
//   }
// }
// EXPORT CLASS CIRCLEPACK EXTENDS (PROTOTYPEPACK AS NEW () => PICK<PROTOTYPEPACK, 
// "_USERENDER" 
// >) { 
//   VIEWPACK = NEW VIEWPACK()

//   BORDERCOLOR = "RGBA(255, 255, 255, 1)"
//   PRESSBORDERCOLOR = "RGBA(166, 166, 166, 1)"

//   VARRUCTOR() {
//     SUPER()
//     THIS.VIEWPACK.ASSIGNSTYLE({
//       DISPLAY: "FLEX",
//       JUSTIFYCONTENT: "CENTER",
//       ALIGNITEMS: "CENTER",
//       WIDTH: 34,
//       HEIGHT: 34,
//       BORDERRADIUS: 52,
//       BORDERWIDTH: 1,
//       BORDERCOLOR: "RGBA(244, 244, 244, 1)",
//       BORDERSTYLE: "SOLID",
//       BACKGROUNDCOLOR: "RGBA(199, 199, 199, 0.5)",
//     })
//   }
//   CIRCLE(PROP: NOPROP) {
//     VAR
//     VIEWPACK = THIS.VIEWPACK
//     THIS._USERENDER()
//     RETURN (
//       <VIEWPACK.VIEW>
//       </VIEWPACK.VIEW>
//     )
//   }
// }
// EXPORT CLASS HORIZONTALANIMATALVIEWPACK EXTENDS (PROTOTYPEPACK AS NEW () => PICK<PROTOTYPEPACK, 
// "_REGISTERPAN" |
// "_REGISTERPANRESPONDERY" |
// "_REGISTERPANANIMATIONENDY" |
// "PANRESPONDER" |
// "GETMERGESTYLE" 
// >) {
//   HORIZONTALANIMATALVIEWPACK = NEW ANIMATALVIEWPACK()
//   VARRUCTOR() {
//     SUPER()
//     THIS.HORIZONTALANIMATALVIEWPACK.ASSIGNSTYLE({
//       LEFT: NEW ANIMATED.VALUE(0),
//       TOP: 0,
//     })
//     THIS._REGISTERPAN()
//     THIS._REGISTERPANANIMATIONENDY()
//     THIS._REGISTERPANRESPONDERY()
//   }
//   HORIZONTALANIMATALVIEW(PROP: BASEWITHCHILDRENPROP) {
//     VAR
//     HORIZONTALANIMATALVIEWPACK = THIS.HORIZONTALANIMATALVIEWPACK
//     RETURN (
//       <HORIZONTALANIMATALVIEWPACK.ANIMATALVIEW
//         { ...THIS.PANRESPONDER.PANHANDLERS }
//       >
//         { PROP.CHILDREN }
//       </HORIZONTALANIMATALVIEWPACK.ANIMATALVIEW>
//     )
//   }
// }
// EXPORT CLASS HORIZONTALPANALVIEWPACK EXTENDS (PROTOTYPEPACK AS NEW () => PICK<PROTOTYPEPACK, 
// "_REGISTERPANRESPONDERX" |
// "_REGISTERPANANIMATIONENDX" |
// "_REGISTERPAN" |
// "ASSIGNSTYLE" |
// "PANRESPONDER"
// >) {
//   HORIZONTALPANALVIEWPACK = NEW ANIMATALVIEWPACK()
//   VARRUCTOR() {
//     SUPER()
//     THIS.ASSIGNSTYLE({
//       LEFT: NEW ANIMATED.VALUE(0),
//       TOP: 0,
//     })
//     THIS._REGISTERPAN()
//     THIS._REGISTERPANANIMATIONENDX()
//     THIS._REGISTERPANRESPONDERX()
//   }
//   HORIZONTALPANALVIEW(PROP: BASEWITHCHILDRENPROP) {
//     VAR
//     HORIZONTALPANALVIEWPACK = THIS.HORIZONTALPANALVIEWPACK
//     RETURN (
//       <HORIZONTALPANALVIEWPACK.ANIMATALVIEW
//         { ...THIS.PANRESPONDER.PANHANDLERS }
//       >
//         { PROP.CHILDREN }
//       </HORIZONTALPANALVIEWPACK.ANIMATALVIEW>
//     )
//   }
// }
// EXPORT CLASS IMAGEPACK EXTENDS (PROTOTYPEPACK AS NEW (PROPS) => PICK<PROTOTYPEPACK, 
// "_USEREF" |
// "_USERENDER" |
// "FADEDURATION" |
// "GETREF" |
// "REND" |
// "SOURCE" |
// "STYLE" 
// >) {
//   VARRUCTOR() {
//     SUPER()
//   }
//   IMAGE(PROP: NOPROP) {
//     THIS._USEREF()
//     THIS._USERENDER()
//     RETURN (
//       <REACTNATIVEIMAGE 
//         FADEDURATION={ THIS.FADEDURATION } 
//         HEIGHT={ THIS.STYLE.HEIGHT } 
//         SOURCE={ THIS.SOURCE } 
//         STYLE={ THIS.STYLE }
//         WIDTH={ THIS.STYLE.WIDTH } 
//       >
//       </REACTNATIVEIMAGE>
//     ) 
//   }
// }
// EXPORT CLASS LISTPACK EXTENDS (PROTOTYPEPACK AS NEW () => PICK<PROTOTYPEPACK, 
// "_USERENDER" |
// "GETREF" |
// "REND" 
// >) {
//   VIEWPACK = NEW VIEWPACK()

//   ITEMS = []
//   RENDERITEM

//   VARRUCTOR() {
//     SUPER()
//     THIS.VIEWPACK.ASSIGNSTYLE({
//       WIDTH: "100%",
//       HEIGHT: "100%",
//     })
//   }
//   CANVASSCROLL(PROP: BASEWITHCHILDRENPROP) {
//     VAR
//     VIEWPACK = THIS.VIEWPACK
//     THIS._USERENDER()
//     RETURN ( 
//       <VIEWPACK.VIEW>
//         { THIS._MAPITEMS() }
//       </VIEWPACK.VIEW>
//     )
//   }
//   _MAPITEMS() {
//     RETURN THIS.ITEMS.MAP((ITEM, INDEX) => THIS.RENDERITEM(ITEM, INDEX))
//   }
// }
// EXPORT CLASS PRESSABLEICONPACK EXTENDS (PROTOTYPEPACK AS NEW () => PICK<PROTOTYPEPACK, 
// "_USERENDER" 
// >) { 
//   VIEWPACK = NEW VIEWPACK()
//   PRESSABLEPACK = NEW PRESSABLEPACK()
//   FAICONPACK = NEW FAICONPACK()
  
//   BORDERCOLOR = "RGBA(255, 255, 255, 1)"
//   PRESSBORDERCOLOR = "RGBA(166, 166, 166, 1)"

//   VARRUCTOR() {
//     SUPER()
//     THIS.VIEWPACK.ASSIGNSTYLE({
//       ALIGNITEMS: "CENTER",
//       BORDERSTYLE: "SOLID",
//       BORDERWIDTH: 1,
//       DISPLAY: "FLEX",
//       JUSTIFYCONTENT: "CENTER",
//       MARGINLEFT: 8,
//       MARGINRIGHT: 8,
//     })
//     THIS.PRESSABLEPACK.ASSIGNSTYLE({
//       ALIGNITEMS: "CENTER",
//       DISPLAY: "FLEX",
//       JUSTIFYCONTENT: "CENTER",
//       PADDING: 8,
//     })
//     THIS.FAICONPACK.ASSIGNSTYLE({
//       WIDTH: 34,
//       HEIGHT: 34,
//       FONTWEIGHT: "BOLD",
//       COLOR: "RGBA(166, 166, 166, 1)",
//     })
//   }
//   PRESSABLEICON(PROP: NOPROP) {
//     VAR 
//     VIEWPACK = THIS.VIEWPACK,
//     PRESSABLEPACK = THIS.PRESSABLEPACK,
//     FAICONPACK = THIS.FAICONPACK
//     THIS._USERENDER()
//     THIS._APPLYRECTANGLEBORDERCOLOR()
//     RETURN (
//       <VIEWPACK.VIEW>
//         <PRESSABLEPACK.PRESSABLE>
//           <FAICONPACK.FAICON></FAICONPACK.FAICON>
//         </PRESSABLEPACK.PRESSABLE>
//       </VIEWPACK.VIEW>
//     )
//   } 
//   _APPLYRECTANGLEBORDERCOLOR() {
//     IF (THIS.PRESSABLEPACK.PRESS) {
//       THIS.VIEWPACK.ASSIGNSTYLE({
//         BORDERCOLOR: THIS.BORDERCOLOR2,
//       })
//     } ELSE {
//       THIS.VIEWPACK.ASSIGNSTYLE({
//         BORDERCOLOR: THIS.BORDERCOLOR,
//       })
//     }
//   }
// }
// EXPORT CLASS PRESSABLECIRCLEPACK EXTENDS (PROTOTYPEPACK AS NEW () => PICK<PROTOTYPEPACK, 
// "_USERENDER" 
// >) { 
//   VIEWPACK = NEW VIEWPACK()
//   PRESSABLEPACK = NEW PRESSABLEPACK()

//   BORDERCOLOR = "RGBA(255, 255, 255, 1)"
//   BORDERCOLOR2 = "RGBA(166, 166, 166, 1)"

//   VARRUCTOR() {
//     SUPER()
//     THIS.VIEWPACK.ASSIGNSTYLE({
//       DISPLAY: "FLEX",
//       JUSTIFYCONTENT: "CENTER",
//       ALIGNITEMS: "CENTER",
//       MARGINLEFT: 8,
//       MARGINRIGHT: 8,
//       BORDERWIDTH: 1,
//       BORDERSTYLE: "SOLID",
//       PADDING: 8,
//     })
//     THIS.PRESSABLEPACK.ASSIGNSTYLE({
//       DISPLAY: "FLEX",
//       JUSTIFYCONTENT: "CENTER",
//       ALIGNITEMS: "CENTER",
//       WIDTH: 34,
//       HEIGHT: 34,
//       BORDERRADIUS: 52,
//       BORDERWIDTH: 1,
//       BORDERCOLOR: "RGBA(244, 244, 244, 1)",
//       BORDERSTYLE: "SOLID",
//       BACKGROUNDCOLOR: "RGBA(199, 199, 199, 0.5)",
//     })
//   }
//   CIRCLE(PROP: NOPROP) {
//     VAR
//     VIEWPACK = THIS.VIEWPACK,
//     PRESSABLEPACK = THIS.PRESSABLEPACK
//     THIS._USERENDER()
//     THIS._APPLYRECTANGLEBORDERCOLOR()
//     RETURN (
//       <VIEWPACK.VIEW>
//         <PRESSABLEPACK.PRESSABLE>
//         </PRESSABLEPACK.PRESSABLE>
//       </VIEWPACK.VIEW>
//     )
//   }
//   _APPLYRECTANGLEBORDERCOLOR() {
//     IF (THIS.PRESSABLEPACK.PRESS) {
//       THIS.VIEWPACK.ASSIGNSTYLE({
//         BORDERCOLOR: THIS.BORDERCOLOR2,
//       })
//     } ELSE {
//       THIS.VIEWPACK.ASSIGNSTYLE({
//         BORDERCOLOR: THIS.BORDERCOLOR,
//       })
//     }
//   }
// }
// EXPORT CLASS PRESSABLEPACK EXTENDS (PROTOTYPEPACK AS NEW (PROPS) => PICK<PROTOTYPEPACK, 
// "_DOONLONGPRESSES" |
// "_DOONPRESSES" |
// "_DOONPRESSOUTS" |
// "_DOONTOUCHENDS" |
// "_DOONTOUCHMOVES" |
// "_DOONTOUCHSTARTS" |
// "_USEREF" |
// "_USERENDER" |
// "ACCESSIBILITYACTIONS" |
// "ACCESSIBILITYHINT" |
// "ACCESSIBILITYLABEL" |
// "ADDONLONGPRESS" |
// "ADDONPRESS" |
// "ADDONPRESSOUT" |
// "ADDONTOUCHEND" |
// "ADDONTOUCHMOVE" |
// "ADDONTOUCHSTART" |
// "ASSIGNSTYLE" |
// "GETREF" |
// "LONGPRESSED" |
// "MEASUREINWINDOW" |
// "PRESS" |
// "REND" |
// "STYLE" |
// "TOOLTIPTEXT" 
// >) {
//   VARRUCTOR() {
//     SUPER()
//     THIS.ASSIGNSTYLE({
//       WIDTH: UNDEFINED,
//       HEIGHT: UNDEFINED,
//       MARGIN: 0,
//       PADDING: 0,
//       BOXSIZING: "BORDER-BOX",
//     })
//   }
//   PRESSABLE(PROP: BASEWITHCHILDRENPROP) { 
//     THIS._USERENDER()
//     THIS._USEREF()
//     RETURN (
//       <REACTNATIVE.PRESSABLE 
//         ACCESSIBILITYACTIONS={ THIS.ACCESSIBILITYACTIONS } 
//         ACCESSIBILITYHINT={ THIS.ACCESSIBILITYHINT } 
//         ACCESSIBILITYLABEL={ THIS.ACCESSIBILITYLABEL } 
//         ONLONGPRESS={ THIS._ONLONGPRESS }
//         ONPRESS={ THIS._ONPRESS } 
//         ONPRESSOUT={ THIS._ONPRESSOUT }
//         REF={ THIS.GETREF() }
//         STYLE={ THIS.STYLE }
//       >
//         { PROP.CHILDREN }
//       </REACTNATIVE.PRESSABLE>
//     )
//   }
//   ASYNC _ONLONGPRESS(O) {
//     THIS.LONGPRESSED = TRUE 
//     THIS._DOONLONGPRESSES(O)
//     VAR { LEFT, TOP, WIDTH, HEIGHT } = THIS.MEASUREINWINDOW()
//     IF (THIS.TOOLTIPTEXT) {
//       TOOLTIPPACK1.SHOW( THIS.TOOLTIPTEXT, {
//         LEFT,
//         TOP,
//         WIDTH,
//         HEIGHT,
//       } )
//     }
//   }
//   ASYNC _ONPRESS(O) {
//     THIS.PRESS = TRUE 
//     THIS._DOONPRESSES(O)
//   }
//   ASYNC _ONPRESSOUT(O) {
//     THIS.PRESS = FALSE
//     THIS.LONGPRESSED = FALSE
//     THIS._DOONPRESSOUTS(O)
//     IF (THIS.TOOLTIPTEXT) {
//       TOOLTIPPACK1.HIDE()
//     }
//   }
// }
// EXPORT CLASS SCROLLVIEWPACK EXTENDS (PROTOTYPEPACK AS NEW (PROPS) => PICK<PROTOTYPEPACK, 
// "_CREATELAYOUTELEMENT" |
// "_DOONCONTENTSIZECHANGES" |
// "_DOONSCROLLANIMATIONENDS" |
// "_DOONSCROLLS" |
// "_USEREF" |
// "_USERENDER" |
// "ACCESSIBILITYACTIONS" |
// "ACCESSIBILITYLABEL" |
// "ADDONCONTENTSIZECHANGE" |
// "ADDONLAYOUT" |
// "ADDONSCROLL" |
// "ADDONSCROLLANIMATIONEND" |
// "ASSIGNCONTENTCONTAINERSTYLE" |
// "ASSIGNOPTION" |
// "ASSIGNSTYLE" |
// "CONTENTCONTAINERSTYLE" |
// "GETREF" |
// "KEYBOARDSHOULDPERSISTTAPS" |
// "MEASUREINWINDOW" |
// "OPTION" |
// "REND" |
// "STYLE" 
// >) {
//   VARRUCTOR() {
//     SUPER()
//     THIS.ASSIGNSTYLE({
//       MARGIN: 0,
//       PADDING: 0,
//     })
//     THIS.ASSIGNCONTENTCONTAINERSTYLE({
//       MARGIN: 0,
//       PADDING: 0,
//     })
//     THIS.ADDONCONTENTSIZECHANGE((O) => {
//       THIS.ASSIGNCONTENTCONTAINERSTYLE({
//         HEIGHT: O.NATIVEEVENT.LAYOUT.HEIGHT,
//       })
//     })
//   }

//   ENABLESCROLL: BOOLEAN

//   SCROLLVIEW(PROP: BASEWITHCHILDRENPROP) {
//     VAR A
//     THIS._USEREF()
//     THIS._USERENDER()
//     A = THIS._CREATELAYOUTELEMENT(PROP)
//     IF (A == UNDEFINED) {
//       THIS.ASSIGNSTYLE({
//         OPACITY: 1,
//       })
//       A = (
//         <REACTNATIVE.SCROLLVIEW 
//           CONTENTCONTAINERSTYLE={ THIS.CONTENTCONTAINERSTYLE }
//           KEYBOARDSHOULDPERSISTTAPS={ THIS.KEYBOARDSHOULDPERSISTTAPS }
//           ONCONTENTSIZECHANGE={ THIS._DOONCONTENTSIZECHANGES }
//           ONSCROLL={ THIS._DOONSCROLLS }
//           ONSCROLLANIMATIONEND={ THIS._DOONSCROLLANIMATIONENDS }
//           REF={ THIS.GETREF() }
//           SCROLLENABLED={ THIS.ENABLESCROLL }
//           STYLE={ THIS.STYLE }
//         >
//           { PROP.CHILDREN }
//         </REACTNATIVE.SCROLLVIEW>
//       )
//     }
//     RETURN A
//   }
// }
// EXPORT CLASS SVGPACK EXTENDS (PROTOTYPEPACK AS NEW (PROPS) => PICK<PROTOTYPEPACK, 
// "_DOONSUBMITEDITINGS" |
// "_DOONTOUCHENDS" |
// "_DOONTOUCHMOVES" |
// "_DOONTOUCHSTARTS" |
// "_REGISTERKEYBOARDEVENTS" |
// "_USEREF" |
// "_USERENDER" |
// "ACCESSIBILITYACTIONS" |
// "ACCESSIBILITYLABEL" |
// "ASSIGNSTYLE" |
// "FILL" |
// "GETREF" |
// "REND" |
// "STYLE" |
// "VALUE" 
// >) {
//   VARRUCTOR() {
//     SUPER()
//     THIS.ASSIGNSTYLE({
//       DISPLAY: "BLOCK",
//       MARGIN: 0,
//       PADDING: 0,
//       BOXSIZING: "BORDER-BOX",
//       OVERFLOW: "AUTO",
//       OPACITY: 0,
//     })
//   }
//   SVG(PROP: BASEWITHCHILDRENPROP) {
//     VAR A
//     THIS._USEREF()
//     THIS._USERENDER()
//     A = (
//       <REACTNATIVESVG
//         ACCESSIBILITYACTIONS={ THIS.ACCESSIBILITYACTIONS }
//         ACCESSIBILITYLABEL={ THIS.ACCESSIBILITYLABEL }
//         FILL={ THIS.FILL } 
//         HEIGHT={ THIS.STYLE.HEIGHT } 
//         ONTOUCHEND={ THIS._DOONTOUCHENDS }
//         ONTOUCHMOVE={ THIS._DOONTOUCHMOVES }
//         ONTOUCHSTART={ THIS._DOONTOUCHSTARTS }
//         REF={ THIS.GETREF() }
//         STYLE={ THIS.STYLE }
//         WIDTH={ THIS.STYLE.WIDTH } 
//       >
//         { PROP.CHILDREN }
//       </REACTNATIVESVG>
//     )
//     RETURN A
//   }
// }
// EXPORT CLASS TEXTPACK EXTENDS (PROTOTYPEPACK AS NEW (PROPS) => PICK<PROTOTYPEPACK, 
// "_USEREF" |
// "_USERENDER" | 
// "ASSIGNSTYLE" |
// "GETREF" |
// "REND" |
// "STYLE" 
// >) {
//   TEXT(PROP: BASEWITHCHILDRENPROP) {
//     THIS._USEREF()
//     THIS._USERENDER()
//     RETURN (
//       <REACTNATIVE.TEXT
//         REF={ THIS.GETREF() }
//         STYLE={ THIS.STYLE }
//       >
//         { PROP.CHILDREN }
//       </REACTNATIVE.TEXT> 
//     )
//   }
// }
// EXPORT CLASS TEXTINPUTPACK EXTENDS (PROTOTYPEPACK AS NEW (PROPS) => PICK<PROTOTYPEPACK, 
// "_DOONBLURS" | 
// "_DOONCHANGETEXTS" |
// "_DOONFOCUSES" |
// "_DOONPRESSES" |
// "_DOONSUBMITEDITINGS" |
// "_REGISTERKEYBOARDEVENTS" |
// "_USEREF" |
// "_USERENDER" |
// "ACCESSIBILITYHINT" |
// "ACCESSIBILITYLABEL" |
// "ALLOWFONTSCALING" |
// "ASSIGNSTYLE" |
// "BLURONSUBMIT" |
// "GETREF" |
// "INPUTMODE" |
// "MAXLENGTH" |
// "PLACEHOLDER" |
// "REND" |
// "STYLE" |
// "VALUE" 
// >) {
//   VARRUCTOR() {
//     SUPER()
//     THIS.ASSIGNSTYLE({
//       BOXSIZING: "BORDER-BOX",
//       DISPLAY: "BLOCK",
//       MARGIN: 0,
//       OVERFLOW: "AUTO",
//       PADDING: 0,
//     })
//     THIS._REGISTERKEYBOARDEVENTS()
//   }
//   TEXTINPUT(PROP: NOPROP) {
//     VAR A
//     THIS._USEREF()
//     THIS._USERENDER()
//     A = (
//       <REACTNATIVE.TEXTINPUT
//         ACCESSIBILITYHINT={ THIS.ACCESSIBILITYHINT }
//         ACCESSIBILITYLABEL={ THIS.ACCESSIBILITYLABEL }
//         ALLOWFONTSCALING={ THIS.ALLOWFONTSCALING }
//         BLURONSUBMIT={ THIS.BLURONSUBMIT }
//         INPUTMODE={ THIS.INPUTMODE }
//         MAXLENGTH={ THIS.MAXLENGTH }
//         ONBLUR={ THIS._DOONBLURS }
//         ONCHANGETEXT={ THIS._DOONCHANGETEXTS }
//         ONFOCUS={ THIS._DOONFOCUSES }
//         ONPRESS={ THIS._DOONPRESSES }
//         ONSUBMITEDITING={ THIS._DOONSUBMITEDITINGS }
//         PLACEHOLDER={ THIS.PLACEHOLDER }
//         REF={ THIS.GETREF() }
//         STYLE={ THIS.STYLE }
//         VALUE={ THIS.VALUE }
//       />
//     )
//     RETURN A
//   }
// }
// EXPORT CLASS TOOLTIPPACK EXTENDS (PROTOTYPEPACK AS NEW () => PICK<PROTOTYPEPACK, 
// "_DOONSCROLLS" |
// "_DOONTOUCHENDS" |
// "_DOONTOUCHMOVES" |
// "_DOONTOUCHSTARTS" |
// "_USEREF" |
// "_USERENDER" |
// "ACCESSIBILITYACTIONS" |
// "ACCESSIBILITYLABEL" |
// "ASSIGNCONTENTCONTAINERSTYLE" |
// "ASSIGNSTYLE" |
// "CONTENTCONTAINERSTYLE" |
// "GETREF" |
// "MEASUREINWINDOW" |
// "REND" |
// "TEXT" |
// "TARGET" |
// "STYLE" 
// >) {
//   TOOLTIPTEXTPACK = NEW TEXTPACK()
//   TOOLTIPVIEWPACK = NEW VIEWPACK()
//   VARRUCTOR() {
//     SUPER()
//     THIS.TOOLTIPVIEWPACK.ASSIGNSTYLE({
//       BACKGROUNDCOLOR: "RGBA(55, 55, 55, 1)",
//       BORDERRADIUS: 52,
//       DISPLAY: "FLEX",
//       FLEXDIRECTION: "ROW",
//       FONTWEIGHT: "BOLD",
//       HEIGHT: UNDEFINED,
//       LEFT: 0,
//       MAXWIDTH: 200,
//       OPACITY: 0,
//       OVERFLOW: "HIDDEN",
//       PADDING: 12,
//       POSITION: "absOLUTE",
//       WHITESPACE: "NOWRAP",
//       WIDTH: UNDEFINED,
//       ZINDEX: UNDEFINED,
//     })
//     THIS.TOOLTIPTEXTPACK.ASSIGNSTYLE({
//       COLOR: "RGBA(255, 255, 255, 1)",
//       FONTSIZE: 24,
//       OVERFLOW: "AUTO",
//       WHITESPACE: "NOWRAP",
//     })
//   }
//   TOOLTIP(PROP: NOPROP) {
//     VAR 
//     TOOLTIPVIEWPACK = THIS.TOOLTIPVIEWPACK,
//     TOOLTIPTEXTPACK = THIS.TOOLTIPTEXTPACK
//     THIS._USERENDER()
//     RETURN (
//       <TOOLTIPVIEWPACK.VIEW>
//         <TOOLTIPTEXTPACK.TEXT>{ THIS.TEXT }</TOOLTIPTEXTPACK.TEXT>
//       </TOOLTIPVIEWPACK.VIEW>
//     )
//   }
//   SHOW(TEXT, TARGET: { 
//     HEIGHT: NUMBER
//     LEFT: NUMBER 
//     TOP: NUMBER 
//     WIDTH: NUMBER 
//   }) {
//     THIS.TEXT = TEXT
//     THIS.TARGET = {
//       HEIGHT: TARGET.HEIGHT,
//       LEFT: TARGET.LEFT,    
//       TOP: TARGET.TOP,
//       WIDTH: TARGET.WIDTH,
//     }
//     THIS.TOOLTIPVIEWPACK.ASSIGNSTYLE({
//       HEIGHT: UNDEFINED,
//       WIDTH: UNDEFINED,
//     })
//     THIS.REND()
//     COMMON.NEXTTICKNOSYNC(() => {
//       VAR { WIDTH, HEIGHT } = THIS.TOOLTIPVIEWPACK.MEASUREINWINDOW()
//       THIS.TOOLTIPVIEWPACK.ASSIGNSTYLE({
//         HEIGHT,
//         WIDTH,
//       })
//       THIS._SHOW()
//     })
//   }
//   HIDE() {
//     THIS.TOOLTIPVIEWPACK.ASSIGNSTYLE({
//       HEIGHT: UNDEFINED,
//       OPACITY: 0,
//       WIDTH: UNDEFINED,
//       ZINDEX: -1,
//     })
//     THIS.REND()
//   }
//   _SHOW() {
//     VAR A, B, C
//     A = {
//       HEIGHT: THIS.TARGET.HEIGHT,
//       LEFT: THIS.TARGET.LEFT,
//       TOP: THIS.TARGET.TOP,
//       WIDTH: THIS.TARGET.WIDTH,
//     }
//     B = {
//       HEIGHT: THIS.TOOLTIPVIEWPACK.STYLE.HEIGHT,
//       WIDTH: THIS.TOOLTIPVIEWPACK.STYLE.WIDTH,
//     }
//     C = GETTEXTAREAPOSITION(A, B)
//     THIS.TOOLTIPVIEWPACK.ASSIGNSTYLE({
//       LEFT: C.LEFT,
//       OPACITY: 1,
//       TOP: C.TOP,
//       ZINDEX: 5,
//     })
//     THIS.REND()
//   }
// }
// EXPORT CLASS VERTICALANIMATALVIEWPACK EXTENDS (PROTOTYPEPACK AS NEW () => PICK<PROTOTYPEPACK, 
// "_REGISTERPAN" |
// "_REGISTERPANRESPONDERY" |
// "_REGISTERPANANIMATIONENDY" |
// "PANRESPONDER" |
// "GETMERGEDSTYLE" 
// >) {
//   VERTICALANIMATALVIEWPACK = NEW ANIMATALVIEWPACK()
//   VARRUCTOR() {
//     SUPER()
//     THIS.VERTICALANIMATALVIEWPACK.ASSIGNSTYLE({
//       LEFT: 0,
//       TOP: NEW ANIMATED.VALUE(0),
//     })
//     THIS._REGISTERPAN()
//     THIS._REGISTERPANANIMATIONENDY()
//     THIS._REGISTERPANRESPONDERY()
//   }
//   VERTICALANIMATALVIEW(PROP: BASEWITHCHILDRENPROP) {
//     VAR
//     VERTICALANIMATALVIEWPACK = THIS.VERTICALANIMATALVIEWPACK
//     RETURN (
//       <VERTICALANIMATALVIEWPACK.ANIMATALVIEW
//         { ...THIS.PANRESPONDER.PANHANDLERS }
//       >
//         { PROP.CHILDREN }
//       </VERTICALANIMATALVIEWPACK.ANIMATALVIEW>
//     )
//   }
// }
// EXPORT CLASS VERTICALPANALVIEWPACK EXTENDS (PROTOTYPEPACK AS NEW (PROPS) => PICK<PROTOTYPEPACK<{
//   CHILDREN,
// }>, 
// "_REGISTERPAN" |
// "_REGISTERPANANIMATIONENDY" |
// "_REGISTERPANRESPONDERY" |
// "ASSIGNSTYLE" |
// "PANRESPONDER" |  
// "PROPS" 
// >) {
//   VARRUCTOR(PROPS) {
//     SUPER(PROPS)
//     THIS.VERTICALPANALVIEWPACK.ASSIGNSTYLE({
//       LEFT: 0,
//       TOP: NEW ANIMATED.VALUE(0),
//     })
//     THIS._REGISTERPAN()
//     THIS._REGISTERPANANIMATIONENDY()
//     THIS._REGISTERPANRESPONDERY()
//   }
//   RENDER() {
//     VAR
//     VERTICALPANALVIEWPACK = THIS.VERTICALPANALVIEWPACK
//     RETURN (
//       <ANIMATALVIEWPACK
//         { ...THIS.PANRESPONDER.PANHANDLERS }
//       >
//         { THIS.PROPS.CHILDREN }
//       </ANIMATALVIEWPACK>
//     )
//   }
// }
// EXPORT CLASS VIEWPACK EXTENDS (PROTOTYPEPACK AS NEW (PROPS) => PICK<PROTOTYPEPACK<{ 
// CHILDREN, 
// STYLE, 
// }>, 
// "_CREATELAYOUTELEMENT" |
// "_DOONTOUCHENDS" |
// "_DOONTOUCHMOVES" |
// "_DOONTOUCHSTARTS" |
// "_REGISTERKEYBOARDEVENTS" |
// "_USEREF" |
// "_USERENDER" |
// "ACCESSIBILITYACTIONS" |
// "ACCESSIBILITYLABEL" |
// "ADDONDOUBLETAP" |
// "ADDONLAYOUT" |
// "ADDONTOUCHEND" |
// "ADDONTOUCHMOVE" |
// "ADDONTOUCHSTART" |
// "ASSIGNSTYLE" |
// "GETREF" |
// "MEASUREINWINDOW" |
// "REMOVEONDOUBLETAP" |
// "REMOVEONLAYOUT" |
// "REMOVEONTOUCHEND" |
// "REMOVEONTOUCHMOVE" |
// "REMOVEONTOUCHSTART" |
// "REND" |
// "PROPS" |
// "STYLE" 
// >) { 
//   VARRUCTOR(PROPS) {
//     SUPER(PROPS)
//     THIS.ASSIGNSTYLE({
//       BOXSIZING: "BORDER-BOX",
//       DISPLAY: "BLOCK",
//       HEIGHT: UNDEFINED,
//       MARGIN: 0,
//       OPACITY: 0,
//       OVERFLOW: "AUTO",
//       PADDING: 0,
//       WIDTH: UNDEFINED,
//     })
//     THIS._REGISTERKEYBOARDEVENTS()
//   }
//   RENDER() {
//     VAR A
//     THIS._USEREF()
//     THIS._USERENDER()
//     A = THIS._CREATELAYOUTELEMENT(THIS.PROPS)
//     IF (A == UNDEFINED) {
//       THIS.ASSIGNSTYLE({
//         OPACITY: 1,
//       })
//       THIS.ASSIGNSTYLE(THIS.PROPS.STYLE)
//       A = (
//         <REACTNATIVE.VIEW
//           ACCESSIBILITYACTIONS={ THIS.ACCESSIBILITYACTIONS }
//           ACCESSIBILITYLABEL={ THIS.ACCESSIBILITYLABEL }
//           ONTOUCHEND={ THIS._DOONTOUCHENDS }
//           ONTOUCHMOVE={ THIS._DOONTOUCHMOVES }
//           ONTOUCHSTART={ THIS.ONTOUCHSTART }
//           REF={ THIS.GETREF() }
//           STYLE={ THIS.STYLE }
//           >
//           { THIS.PROPS.CHILDREN }
//         </REACTNATIVE.VIEW>
//       )
//     }
//     RETURN A
//   }
// }
// EXPORT CLASS VIEWPACK EXTENDS (PROTOTYPEPACK AS NEW (PROPS) => PICK<PROTOTYPEPACK<{ 
// CHILDREN, 
// STYLE, 
// }>, 
// "_CREATELAYOUTELEMENT" |
// "_DOONTOUCHENDS" |
// "_DOONTOUCHMOVES" |
// "_DOONTOUCHSTARTS" |
// "_REGISTERKEYBOARDEVENTS" |
// "_USEREF" |
// "_USERENDER" |
// "ACCESSIBILITYACTIONS" |
// "ACCESSIBILITYLABEL" |
// "ADDONDOUBLETAP" |
// "ADDONLAYOUT" |
// "ADDONTOUCHEND" |
// "ADDONTOUCHMOVE" |
// "ADDONTOUCHSTART" |
// "ASSIGNSTYLE" |
// "GETREF" |
// "MEASUREINWINDOW" |
// "REMOVEONDOUBLETAP" |
// "REMOVEONLAYOUT" |
// "REMOVEONTOUCHEND" |
// "REMOVEONTOUCHMOVE" |
// "REMOVEONTOUCHSTART" |
// "REND" |
// "PROPS" |
// "STYLE" 
// >) { 
//   VARRUCTOR(PROPS) {
//     SUPER(PROPS)
//     THIS.ASSIGNSTYLE({
//       BOXSIZING: "BORDER-BOX",
//       DISPLAY: "BLOCK",
//       HEIGHT: UNDEFINED,
//       MARGIN: 0,
//       OPACITY: 0,
//       OVERFLOW: "AUTO",
//       PADDING: 0,
//       WIDTH: UNDEFINED,
//     })
//     THIS._REGISTERKEYBOARDEVENTS()
//   }
//   RENDER() {
//     VAR A
//     THIS._USEREF()
//     THIS._USERENDER()
//     A = THIS._CREATELAYOUTELEMENT(THIS.PROPS)
//     IF (A == UNDEFINED) {
//       THIS.ASSIGNSTYLE({
//         OPACITY: 1,
//       })
//       THIS.ASSIGNSTYLE(THIS.PROPS.STYLE)
//       A = (
//         <REACTNATIVE.VIEW
//           ACCESSIBILITYACTIONS={ THIS.ACCESSIBILITYACTIONS }
//           ACCESSIBILITYLABEL={ THIS.ACCESSIBILITYLABEL }
//           ONTOUCHEND={ THIS._DOONTOUCHENDS }
//           ONTOUCHMOVE={ THIS._DOONTOUCHMOVES }
//           ONTOUCHSTART={ THIS.ONTOUCHSTART }
//           REF={ THIS.GETREF() }
//           STYLE={ THIS.STYLE }
//           >
//           { THIS.PROPS.CHILDREN }
//         </REACTNATIVE.VIEW>
//       )
//     }
//     RETURN A
//   }
// }
// EXPORT CLASS IMAGEPICKER EXTENDS (PROTOTYPE AS NEW () => PICK<PROTOTYPE, 
// "_NO"
// >) {
//   ASSETS = UNDEFINED
//   OPTION = {
//     MEDIATYPES: REACTNATIVEIMAGEPICKER.MEDIATYPEOPTIONS.ALL,
//     ALLOWSEDITING: FALSE,
//     ASPECT: [4, 3],
//     QUALITY: 1,
//     SELECTIONLIMIT: 1,
//     ALLOWSMULTIPLESELECTION: FALSE,
//   }
//   ASYNC PICKIMAGE(OPTION) {
//     // NO PERMISSIONS REQUEST IS NECESSARY FOR LAUNCHING THE IMAGE LIBRARY
//     VAR A, B
//     A = OBJECT.ASSIGN(OPTION, THIS.OPTION)
//     B = AWAIT REACTNATIVEIMAGEPICKER.LAUNCHIMAGELIBRARYASYNC(A)
//     IF (B.CANCELED) {
//     } ELSE {
//       THIS.ASSETS = B.ASSETS
//     }
//   }
// }
EXPORT CLASS WORKSPACEFILEMANAGER EXTENDS (PROTOTYPE AS NEW () => PICK<PROTOTYPE, 
"_NO"
>) {
  CONTENT: STRING
  DOCUMENTURI: STRING
  FILENAME: STRING
  FILEURI: STRING
  WORKSPACENAME: STRING
  WORKSPACEURI: STRING
  VARRUCTOR() { SUPER(), THIS.DOCUMENTURI = EXPOFILESYSTEM.DOCUMENTDIRECTORY }
  ASYNC CREATEWORKSPACENOSYNC() { VAR A = AWAIT THIS.EXISTWORKSPACENOSYNC(); IF (A) { } ELSE { AWAIT EXPOFILESYSTEM.MAKEDIRECTORYASYNC(THIS.GETWORKSPACEURI()) } }
  ASYNC DELETEFILENOSYNC() { AWAIT EXPOFILESYSTEM.DELETEASYNC(THIS.GETFILEURI()) }
  ASYNC EXISTFILENOSYNC() { VAR A, B; A = AWAIT THIS.LISTWORKSPACENOSYNC(), B = A.INCLUDES(THIS.FILENAME); RETURN B }
  ASYNC EXISTWORKSPACENOSYNC() { VAR A, B; A = AWAIT THIS.LISTDOCUMENTDIRECTORYNOSYNC(), B = A.INCLUDES(THIS.WORKSPACENAME); RETURN B }
  ASYNC GETPOSSIBLESTORAGESIZENOSYNC() { VAR A, B; A = AWAIT EXPOFILESYSTEM.GETFREEDISKSTORAGEASYNC(), B = COMMON.CONVERTSBYTESTOGIGABYTES(A); RETURN B }
  ASYNC LISTDOCUMENTDIRECTORYNOSYNC() { RETURN AWAIT EXPOFILESYSTEM.READDIRECTORYASYNC(THIS.DOCUMENTURI) }
  ASYNC LISTWORKSPACENOSYNC() { RETURN AWAIT EXPOFILESYSTEM.READDIRECTORYASYNC(THIS.GETWORKSPACEURI()) }
  ASYNC READFILEBASE64NOSYNC() { VAR A = AWAIT THIS.READFILENOSYNC({ ENCODING: EXPOFILESYSTEM.ENCODINGTYPE.BASE64, }); RETURN A }
  ASYNC READFILENOSYNC(OPTIONS = {}) { VAR A, B; A = AWAIT THIS.EXISTFILENOSYNC(); IF (A) { B = AWAIT EXPOFILESYSTEM.READASSTRINGASYNC(THIS.FILEURI, OPTIONS) } ELSE { B = "" }; RETURN B }
  ASYNC WRITEFILENOSYNC(TEXT = "") { AWAIT EXPOFILESYSTEM.WRITEASSTRINGASYNC(THIS.GETFILEURI(), TEXT) }
  GETFILEURI() { VAR A; IF (COMMON.ISVALIDSTRING(THIS.GETWORKSPACEURI()) && COMMON.ISVALIDSTRING(THIS.FILENAME)) { A = THIS.GETWORKSPACEURI() + "/" + THIS.FILENAME } RETURN A }
  GETWORKSPACEURI() { VAR A; IF (COMMON.ISVALIDSTRING(THIS.DOCUMENTURI) && COMMON.ISVALIDSTRING(THIS.WORKSPACENAME)) { A = THIS.DOCUMENTURI + "/" + THIS.WORKSPACENAME } RETURN A }
  PARSEFILEURI(FILEURI = "") { VAR A, B, C; A = COMMON.SPLITSTEXTBYSTRING(FILEURI, "/", FALSE), B = COMMON.SPLITSTEXTBYSTRING(A[0], "/", FALSE), THIS.WORKSPACENAME = B[1], THIS.FILENAME = A[1] }
}
// INTERFACE BASEWITHCHILDRENPROP {
//   CHILDREN?
//   [KEY: STRING]: ANY
// }
// INTERFACE BASEPROP {
//   [KEY: STRING]: ANY
// }
// TYPE NOPROP = {
// }
// EXPORT VAR
// TOOLTIPPACK1 = NEW TOOLTIPPACK(), 
// HANDLING = {
//   PACK: {},
//   TOUCHAL: {
//     CURRENT: {
//       COMPONENTID: UNDEFINED,
//     },
//   },
// },
// INFO = {
//   ACCESSIBILITY: {
//     ISSCREENREADERENABLED: UNDEFINED,
//   },
//   OS: {
//     NAME: PLATFORM.OS,
//   },
// },
// KEYBOARD = {
//   METRICS: {
//     HEIGHT: UNDEFINED,
//     WIDTH: UNDEFINED
//   },
//   SHOWING: FALSE
// },
// TRANSLATION = COMMON.FLATSOBJECT(TRANSLATION),
// LOCALE = EXPOLOCALIZATION.GETLOCALES()[0],
// SCREEN = { 
//   HEIGHT: DIMENSIONS.GET("WINDOW").HEIGHT,
//   WIDTH: DIMENSIONS.GET("WINDOW").WIDTH,
// },
// THROTTLE = { 
//   ONTOUCHENDID: COMMON.MAKESAUTOINDEX(),
// }
// {
//   KEYBOARD.ADDLISTENER("KEYBOARDDIDSHOW", () => {
//     KEYBOARD.SHOWING = TRUE
//     KEYBOARD.METRICS = KEYBOARD.METRICS()
//     // CONSOLE.LOG("KEYBOARD METRICS",
//     //   KEYBOARD.METRICS())
//   })
//   KEYBOARD.ADDLISTENER("KEYBOARDDIDHIDE", () => {
//     KEYBOARD.SHOWING = FALSE
//     KEYBOARD.METRICS = {
//       HEIGHT: UNDEFINED,
//       WIDTH: UNDEFINED,
//     }
//   })
//   CONSOLE.LOG(LOCALE.LANGUAGECODE)
//   CONSOLE.LOG(LOCALE.REGIONCODE)
//   CONSOLE.LOG(TRANSLATION)
// }
// EXPORT FUNCTION CALCULATESCREENDIMENSION() {
//   SCREEN.WIDTH = DIMENSIONS.GET("WINDOW").WIDTH
//   SCREEN.HEIGHT = DIMENSIONS.GET("WINDOW").HEIGHT
// }
// EXPORT FUNCTION DOPROTOTYPEVARRUCTOR(PACKMANAGER: PACKMANAGER, PACK) {
//   RETURN NEW PROMISE(ASYNC (resolve, reject) => {
//     PACKMANAGER.PAKCS.PUSH(PACK)
//     PACK.ADDONTOUCHSTART(ASYNC (O) => {
//       PACKMANAGER.TOUCHINGCOMPONENTID = PACK.COMPONENTID
//     })
//     PACK.ADDONTOUCHEND(ASYNC (O) => {
//       PACKMANAGER.TOUCHINGCOMPONENTID = UNDEFINED
//     })
//     PACK.ADDONTOUCHSTART(ASYNC (O) => {
//       PACK.DOUBLETAPPINGCOUNT = PACK.DOUBLETAPPINGCOUNT + 1
//       COMMON.DEBOUNCES(
//         PACK.DOUBLETAPPINGDEBOUNCEID, 
//         () => {
//           PACK.DOUBLETAPPINGCOUNT = 0
//         },
//         PACK.DOUBLETAPPINGDEBOUNCETIMEOUTMILLISECOND,
//       )
//       IF (PACK.DOUBLETAPPINGCOUNT >= 2) {
//         PACK._DOONDOUBLETAPS(O)
//       }
//     })
//     resolve(UNDEFINED)
//   })
// }
// EXPORT FUNCTION DOPROTOTYPEVARRUCTORS(PACKMANAGER: PACKMANAGER, PACKS: []) {
//   RETURN NEW PROMISE(ASYNC (resolve, reject) => {
//     VAR A
//     FOR (A OF PACKS) {
//       DOPROTOTYPEVARRUCTOR(PACKMANAGER, A)
//     }
//     resolve(UNDEFINED)
//   })
// }
// EXPORT FUNCTION GETLOCALIZETEXT(CODE) {
//   VAR A, B, C, D, E
//   A = CODE + "." + LANGUAGE.CODE
//   B = LANGUAGE.FLATTEDPACK[A]
//   IF (B == UNDEFINED || B.TRIM() == "") {
//     C = CODE + "." + "EN"
//     D = LANGUAGE.FLATTEDPACK[C]
//     IF (D == UNDEFINED || D.TRIM() == "") {
//       E = CODE
//     } ELSE {
//       E = D
//     }
//   } ELSE {
//     E = B
//   }
//   RETURN E
// }
// // TARGET: TARGET AREA
// // TARGET2: TOOLTIP AREA
// EXPORT FUNCTION GETTEXTAREAPOSITION(TARGET: { 
//   HEIGHT 
//   LEFT
//   TOP
//   WIDTH 
// }, TARGET2: { 
//   HEIGHT 
//   WIDTH 
// }): { 
//   LEFT: NUMBER 
//   TOP: NUMBER
// } {
//   VAR A, B, C, D, E, F, G, H, I, J, Z
//   Z = { 
//     TOP: -1, 
//     LEFT: -1, 
//     WIDTH: TARGET2.WIDTH, 
//     HEIGHT: TARGET2.HEIGHT 
//   }
//   A = TARGET.TOP - TARGET2.HEIGHT
//   B = __GETADJUSTPAGETOP(A, TARGET, TARGET2)
//   Z.TOP = B
//   IF (B == A) {
//     D = TARGET.LEFT
//     H = __GETADJUSTPAGELEFT(D, TARGET, TARGET2)
//   } ELSE {
//     C = TARGET2.WIDTH
//     D = TARGET.LEFT
//     E = D - C
//     F = TARGET.WIDTH
//     H = __GETADJUSTPAGELEFT2(E, TARGET, TARGET2)
//     I = H + C
//     IF (I > SCREEN.WIDTH) {
//       J = TARGET.TOP + TARGET.HEIGHT
//       Z.TOP = J
//       D = TARGET.LEFT
//       G = TARGET2.WIDTH
//       H = __GETADJUSTPAGELEFT3(D, TARGET, TARGET2)
//     } ELSE {
//       H = H + 4
//     }
//   }
//   Z.LEFT = H
//   RETURN Z
//   FUNCTION _GETPOSSIBLEPAGETOP(TARGET, TARGET2) {
//     VAR A, B
//     A = 0
//     B = SCREEN.HEIGHT - TARGET2.HEIGHT
//     RETURN [A, B]
//   }
//   FUNCTION __GETADJUSTPAGETOP(TOP, TARGET, TARGET2) {
//     VAR A, B
//     A = _GETPOSSIBLEPAGETOP(TARGET, TARGET2)
//     IF (TOP < A[0]) {
//       B = A[0]
//     } ELSE IF (TOP > A[1]) {
//       B = A[1]
//     } ELSE {
//       B = TOP
//     }
//     RETURN B
//   }
//   FUNCTION __GETADJUSTPAGELEFT(LEFT, TARGET, TARGET2) {
//     VAR A, B
//     B = SCREEN.WIDTH - TARGET2.WIDTH
//     IF (LEFT < 0) {
//       A = 0
//     } ELSE IF (LEFT > B) {
//       A = B
//     } ELSE {
//       A = LEFT
//     }
//     RETURN A
//   }
//   FUNCTION __GETADJUSTPAGELEFT2(LEFT, TARGET, TARGET2) {
//     VAR A, B
//     IF (LEFT < 0) {
//       A = TARGET.PAGELEFT + TARGET.WIDTH
//     } ELSE {
//       A = LEFT
//     }
//     IF (A == LEFT) {
//       B = A
//     } ELSE {
//       B = TARGET.PAGELEFT + TARGET.WIDTH
//     }
//     RETURN B
//   }
//   FUNCTION __GETADJUSTPAGELEFT3(LEFT, TARGET, TARGET2) {
//     VAR A
//     A = __GETADJUSTPAGELEFT(LEFT, TARGET, TARGET2)
//     RETURN A
//   }
// }
// EXPORT FUNCTION MOVEBYTIMING(VALUEXY, TO: {
//   X
//   Y
// }, OPTION = {
//   MILLISECOND: 200, 
//   MULTIPLEMILLISECOND: FALSE, 
//   ACCELERATION: 1
// }) {
//   VAR 
//   LEFT,
//   TOP
//   LEFT = {
//     DISTANCE: UNDEFINED,
//     MILLISECOND: UNDEFINED,
//     DURATION: UNDEFINED,
//   }
//   TOP = {
//     DISTANCE: UNDEFINED,
//     MILLISECOND: UNDEFINED,
//     DURATION: UNDEFINED,
//   }
//   IF (TO.X && VALUEXY.LEFT) {
//     LEFT.DISTANCE = Math.abs(TO.X.__GETVALUE() - VALUEXY.LEFT.__GETVALUE())
//     IF (OPTION.MULTIPLEMILLISECOND) {
//       LEFT.MILLISECOND = COMMON.GETSMULTIPLEMILLISECOND(LEFT.DISTANCE, OPTION.MILLISECOND)
//     } ELSE {
//       LEFT.MILLISECOND = OPTION.MILLISECOND
//     }
//     LEFT.DURATION = LEFT.MILLISECOND * OPTION.ACCELERATION
//   }
//   IF (TO.Y && VALUEXY.TOP) {
//     TOP.DISTANCE = Math.abs(TO.Y.__GETVALUE() - VALUEXY.TOP.__GETVALUE())
//     IF (OPTION.MULTIPLEMILLISECOND) {
//       TOP.MILLISECOND = COMMON.GETSMULTIPLEMILLISECOND(TOP.DISTANCE, OPTION.MILLISECOND)
//     } ELSE {
//       TOP.MILLISECOND = OPTION.MILLISECOND
//     }
//     TOP.DURATION = TOP.MILLISECOND * OPTION.ACCELERATION
//   }
//   ANIMATED.TIMING(VALUEXY, {
//     TOVALUE: NEW ANIMATED.VALUEXY({ 
//       X: TO.X, 
//       Y: TO.Y 
//     }),
//     DURATION: TOP.DURATION,
//     USENATIVEDRIVER: FALSE,
//   }).START()
// }
// EXPORT FUNCTION USEONCE(CALL) {
//   REACT.USEEFFECT(() => {
//     CALL()
//   }, [])
// }
// EXPORT FUNCTION USERENDER() {
//   VAR [CONTEXT, SETCONTEXT] = USECONTEXT(() => { RETURN 0 }), B = () => {
//     SETCONTEXT(CONTEXT + 1)
//   }
//   RETURN B
// }